apiVersion: v1
kind: Secret
metadata:
  name: comictracker-secret
type: Opaque
stringData:
  DATABASE_URL: "replace-me"
  DIRECT_URL: "replace-me"
  APP_USERNAME: "replace-me"
  APP_PASSWORD_HASH: "replace-me"
  SESSION_SECRET: "replace-me"
